### ISSUE TITLE
Program for decimal expansions of square roots

### ISSUE THREAD

**Issue by ckrause** [loda-lang/loda-programs#5]
It would be helpful to manually implement LODA programs for decimal expansions of common square roots. For instance we don't have any programs for the sequences listed below. Assumption is that one program would suffice (the others should be derivable). Maybe use the Babylonian Method with separate memory cells for numerator and denominator? See also https://en.wikipedia.org/wiki/Methods_of_computing_square_roots

A010464: Decimal expansion of square root of 6.
A010465: Decimal expansion of square root of 7.
A010466: Decimal expansion of square root of 8.
A010467: Decimal expansion of square root of 10.
A010468: Decimal expansion of square root of 11.
A010469: Decimal expansion of square root of 12.
A010470: Decimal expansion of square root of 13.
A010471: Decimal expansion of square root of 14.
A010472: Decimal expansion of square root of 15.
A010473: Decimal expansion of square root of 17.
A010474: Decimal expansion of square root of 18.
A010475: Decimal expansion of square root of 19.
A010476: Decimal expansion of square root of 20.
A010477: Decimal expansion of square root of 21.
A010478: Decimal expansion of square root of 22.
A010479: Decimal expansion of square root of 23.
A010480: Decimal expansion of square root of 24.
A010481: Decimal expansion of square root of 26.
A010482: Decimal expansion of square root of 27.
A010483: Decimal expansion of square root of 28.
A010484: Decimal expansion of square root of 29.
A010485: Decimal expansion of square root of 30.
A010486: Decimal expansion of square root of 31.
A010487: Decimal expansion of square root of 32.
A010488: Decimal expansion of square root of 33.
A010489: Decimal expansion of square root of 34.
A010490: Decimal expansion of square root of 35.
A010491: Decimal expansion of square root of 37.
A010492: Decimal expansion of square root of 38.
A010493: Decimal expansion of square root of 39.
A010494: Decimal expansion of square root of 40.
A010495: Decimal expansion of square root of 41.
A010496: Decimal expansion of square root of 42.
A010497: Decimal expansion of square root of 43.
A010498: Decimal expansion of square root of 44.
A010499: Decimal expansion of square root of 45.
A010500: Decimal expansion of square root of 46.
A010501: Decimal expansion of square root of 47.
A010502: Decimal expansion of square root of 48.
A010503: Decimal expansion of 1/sqrt(2).
A010504: Decimal expansion of square root of 51.
A010505: Decimal expansion of square root of 52.
A010506: Decimal expansion of square root of 53.
A010507: Decimal expansion of square root of 54.
A010508: Decimal expansion of square root of 55.
A010509: Decimal expansion of square root of 56.
A010510: Decimal expansion of square root of 57.
A010511: Decimal expansion of square root of 58.
A010512: Decimal expansion of square root of 59.
A010513: Decimal expansion of square root of 60.
A010514: Decimal expansion of square root of 61.
A010515: Decimal expansion of square root of 62.
A010516: Decimal expansion of square root of 63.
A010517: Decimal expansion of square root of 65.
A010518: Decimal expansion of square root of 66.
A010519: Decimal expansion of square root of 67.
A010520: Decimal expansion of square root of 68.
A010521: Decimal expansion of square root of 69.
A010522: Decimal expansion of square root of 70.
A010523: Decimal expansion of square root of 71.
A010524: Decimal expansion of square root of 72.
A010525: Decimal expansion of square root of 73.
A010526: Decimal expansion of square root of 74.
A010527: Decimal expansion of sqrt(3)/2.
A010528: Decimal expansion of square root of 76.
A010529: Decimal expansion of square root of 77.
A010530: Decimal expansion of square root of 78.
A010531: Decimal expansion of square root of 79.
A010532: Decimal expansion of square root of 80.
A010533: Decimal expansion of square root of 82.
A010534: Decimal expansion of square root of 83.
A010535: Decimal expansion of square root of 84.
A010536: Decimal expansion of square root of 85.
A010537: Decimal expansion of square root of 86.
A010538: Decimal expansion of square root of 87.
A010539: Decimal expansion of square root of 88.
A010540: Decimal expansion of square root of 89.
A010541: Decimal expansion of square root of 90.
A010542: Decimal expansion of square root of 91.
A010543: Decimal expansion of square root of 92.
A010544: Decimal expansion of square root of 93.
A010545: Decimal expansion of square root of 94.
A010546: Decimal expansion of square root of 95.
A010547: Decimal expansion of square root of 96.
A010548: Decimal expansion of square root of 97.
A010549: Decimal expansion of square root of 98.
A010550: Decimal expansion of square root of 99.

**Comment by ckrause** [comment]
done

**Comment by neoneye** [comment]
awesome!
